server:
  port: 8088

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://10.6.8.236:3306/isales?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=true&serverTimezone=UTC
    username: ro
    password: ny38XjtCo
    #url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=true&serverTimezone=UTC
    #password: admin



mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl